# Generated by Django 4.0.5 on 2022-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_empleado_hoja_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
    ]
